# Generated by Django 2.0.3 on 2018-04-11 17:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='nom')),
                ('_account_number', models.SmallIntegerField(unique=True, verbose_name='numero de compte')),
            ],
            options={
                'verbose_name': 'Banque',
            },
        ),
        migrations.CreateModel(
            name='BankLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField(verbose_name='date de transaction')),
                ('wording', models.CharField(max_length=128, verbose_name='libelle')),
                ('transaction_number', models.CharField(max_length=64, unique=True, verbose_name='numero de transaction')),
                ('debit', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MaxValueValidator(0)], verbose_name='debit')),
                ('credit', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='credit')),
                ('bank_detail', models.CharField(blank=True, max_length=255, verbose_name='détail de la banque')),
                ('user_comment', models.CharField(blank=True, max_length=255, verbose_name='commentaire des utilisateurs')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banklinemanager.Bank')),
            ],
            options={
                'verbose_name': 'Ligne Banque',
            },
        ),
    ]
